### ISSUE TITLE
Feature request: query objectPath of IProxy/ProxyInterfaces

### ISSUE THREAD

**Issue by ChristianS99** [Kistler-Group/sdbus-cpp#104]
Reasoning:
org.freedesktop.DBus.ObjectManager provides InterfacesAdded/Removed signals, that provide the objectPath. Creating sdbus proxy objects with path is easily doable, but if an object is removed, there is no way to compare the path of the removed object with my sdbus::IProxy objects to remove the corresponding object.

Proposal: implement getPath() (and possibly operator sdbus::ObjectPath()) for (I)Proxy and possibly for ProxyInterfaces.
I can do that, just wanted to ask for comments beforehand.

PS: If I have missed s.th. and this is already possible, please point me to it :)

**Comment by sangelovic** [comment]
One of the ways to solve this would be to keep a dictionary of `Proxy`s, with the key being the object path. But I understand this adds a bit of data duplication, and may not be the acceptable solution in all cases. So I'm OK with providing object path information in the public API, since this information is anyway provided by the client when constructing the instance.

We can also add the `getObjectPath` method to `IObject`, not only `IProxy`. And as you mention correctly, also a method with the same name to `AdaptorInterfaces` and `ProxyInterfaces`, delegating to the underlying object/proxy. I would refrain from conversion operator. And the return value of the metho may be `std::string`, so we are type-consistent with factory methods where it is string. `ObjectPath` as a type is used for values of D-Bus types sent to the bus.

Would you volunteer to prepare a merge request? ;)

**Comment by ChristianS99** [comment]
Yes, will prepare a PR

**Comment by ChristianS99** [comment]
Implemented by ae8849e
