### ISSUE TITLE
Request for more example code

### ISSUE THREAD

**Issue by wpd** [Kistler-Group/sdbus-cpp#155]
Aside, I wish you had a "Discussions" section, as this is not an issue with your code, but is instead a pitiful cry for help from a clueless user (me).

Can you point me at more examples of how to use your library?  Specifically (because I'm only on step 1 of my project), I would like to know how I can invoke the `org.freedesktop.DBus.ObjectManager.GetManagedObjects` method on a DBus object (and, more specifically, on the `org.bluez` object).

It seems from reading [this](https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces-objectmanager), that `GetManagedObjects()` returns `DICT<OBJPATH,DICT<STRING,DICT<STRING,VARIANT>>>` and that I would probably need to do something like:
```
    {
        auto getManagedObjects = bluezProxy->createMethodCall("org.freedesktop.DBus.ObjectManager", "GetManagedObjects");
        auto reply = bluezProxy->callMethod(getManagedObjects);
        std::map<std::string, SOMETHING_VERY_UGLY_HERE> result;
        reply >> result;
        for (const auto &[key, value] : result)
        {
            std::cout << "key: " << std::endl;
        }
    }
```
It also seems like there should be an easier way to do this with a high level library such as sdbus-c++.  So I feel like I'm missing something fundamental.

Any and all clues are appreciated.

--wpd

**Comment by riuriuriu** [comment]
Discussions are enabled now. Feel free be the first person to ask a question there. 

I will keep this issue open as a bug as we could indeed add a code example for each standard interface.

About the object manager, have a look at: 
https://github.com/Kistler-Group/sdbus-cpp/blob/master/include/sdbus-c%2B%2B/StandardInterfaces.h#L143
And the existing description of StandardInterfaces in the tutorial: 
https://github.com/Kistler-Group/sdbus-cpp/blob/master/docs/using-sdbus-c++.md#standard-d-bus-interfaces

**Comment by sangelovic** [comment]
We also have integration tests as a form of examples of how to use the library. They are always up-to-date, always working, and they show more -- you can see what's the expected behavior given the inputs, for example. You can look into https://github.com/Kistler-Group/sdbus-cpp/blob/master/tests/integrationtests/DBusStandardInterfacesTests.cpp file, this file lists all test cases for standard interfaces. For the ObjectManager test cases from the proxy perspective, just look at these test cases in that file:

TEST_F(SdbusTestObject, GetsZeroManagedObjectsIfHasNoSubPathObjects)
TEST_F(SdbusTestObject, GetsManagedObjectsSuccessfully)

Perhaps instead of adding example for each standard interface (which is a generic D-Bus level of abstraction, not sdbus-c++, and the use of interfaces in sdbus-c++ is quite explained and shown in the tutorial, so this would seem to me as a duplication of what the user can infer from other sources already, creating additional maintenance burden), we could point the tutorial reader to the *real* *working* examples in the integration tests, by linking these in the given section of the tutorial. What do you think, @riuriuriu?

**Comment by dakhouya** [comment]
About the tests, is there a way to mock completely a  sdbus::IConnection to be able to test an object that is extended from an adaptor without having a real dbus connection? Would there be an example for this? My specific case is that I run unit tests from a docker environment.

Mock example:
```
class MockSdbusConnection : public sdbus::IConnection {
public:
    MockSdbusConnection() = default;
    ~MockSdbusConnection() override = default;
    MOCK_METHOD1(requestName, void(const std::string& name));
    MOCK_METHOD1(releaseName, void(const std::string& name));
    MOCK_CONST_METHOD0(getUniqueName, std::string());
    MOCK_METHOD0(enterEventLoop, void());
    MOCK_METHOD0(enterEventLoopAsync, void());
    MOCK_METHOD0(leaveEventLoop, void());
    MOCK_METHOD1(addObjectManager, void(const std::string& objectPath));
    MOCK_CONST_METHOD0(getEventLoopPollData, PollData());
    MOCK_METHOD0(processPendingRequest, bool());
    MOCK_METHOD1(setMethodCallTimeout, void(uint64_t timeout));
    MOCK_CONST_METHOD0(getMethodCallTimeout, uint64_t());
};
```
Whitout providing any `EXPECT_CALL` I'm getting `"[org.freedesktop.DBus.Error.InvalidArgs] Connection is not a real sdbus-c++ connection (Invalid argument)"`.

**Comment by riuriuriu** [comment]
@sangelovic Agree with linking the tests as examples.

**Comment by riuriuriu** [comment]
@dakhouya Please don't [hijack the thread](https://en.wiktionary.org/wiki/threadjacking). For general questions, you can start a discussion in the discussions section.

**Comment by dakhouya** [comment]
> @dakhouya Please don't [hijack the thread](https://en.wiktionary.org/wiki/threadjacking). For general questions, you can start a discussion in the discussions section.

Sorry I thought this issue was for discussion.
