### ISSUE TITLE
Consider transferring exceptions from internal event loops

### ISSUE THREAD

**Issue by sangelovic** [Kistler-Group/sdbus-cpp#178]
The proposal is laid out in the discussion in this merge request: https://github.com/Kistler-Group/sdbus-cpp/pull/157

We can consider to use `std::exception_ptr` to transfer exceptions from the sdbus-c++ internal event loop thread out to the main thread upon joining. We can keep the destructors noexcept, so exceptions in this case would terminate the program, but provide the other option, too: clients can design their code so that master thread joins with the event loop thread explicitly before invoking a destructor of proxy/connection. For that, we need to extend `IProxy` to provide `getConnection()` method. Then clients have the freedom to react to potential exceptions.

**Comment by dleeds-cpi** [comment]
There is a subset of conditions that may throw exceptions where catching the exception within the library is appropriate.

Specifically, if the exception is thrown due to an asynchronously received incoming message not having the expected payload, it should be ignored. This is a use case where no action can be taken by the recipient of a malformed message to mitigate the issue, and it should just be dropped.

This should be done in the following places:
1. `SignalSubscriber::call`
2. `AsyncMethodInvoker::uponReplyInvoke()`

**Comment by sangelovic** [comment]
It's actually not a good idea that sdbus-c++ exceptions propagate all the way to the event loop itself. This would mean propagating through libsystemd, which is a C library, and this is utterly unsafe. Hence, in the proposed #196, these exceptions are caught in the `Proxy` handlers. Other exceptions are ignored (the clients should take care they are not thrown, or their emission means something has gone very much wrong).
