### ISSUE TITLE
GetManagedObjects returns empty list

### ISSUE THREAD

**Issue by akemnade** [Kistler-Group/sdbus-cpp#247]
GetManagedObjects returns an empty list
`
method call time=1645375156.489775 sender=:1.7375 -> destination=:1.7381 serial=170 path=/org/ak/bleuart/bleprofile; interface=org.freedesktop.DBus.ObjectManager; member=GetManagedObjects
method return time=1645375156.492798 sender=:1.7381 -> destination=:1.7375 serial=3 reply_serial=170
   array [
   ]
error time=1645375156.494406 sender=:1.7375 -> destination=:1.7381 error_name=org.bluez.Error.Failed reply_serial=2
   string "No object received"
`

Example code:
`
        auto connection = sdbus::createSystemBusConnection();
        auto proxy = sdbus::createProxy(*connection, "org.bluez", "/");
        std::map<std::string,sdbus::ObjectPath> chars;
        sdbus::ObjectPath devicepath;
        
        connection->enterEventLoopAsync();
        auto profile = sdbus::createObject(*connection, "/org/ak/bleuart/bleprofile");
        profile->registerProperty("UUIDs").onInterface("org.bluez.GattProfile1").withGetter([](){ return std::vector<std::string>({std::string("374a72cb-f2e8-b15d-2176-046810a1e029")});});

        profile->registerMethod("release").onInterface("org.bluez.GattProfile1").implementedAs([]() { std::cerr << "profile release\n";});
        profile->finishRegistration();
        profile->addObjectManager();
        auto manager = sdbus::createProxy(*connection, "org.bluez", "/org/bluez/hci0");
        manager->callMethodAsync("RegisterApplication").onInterface("org.bluez.GattManager1").withArguments(sdbus::ObjectPath("/org/ak/bleuart/bleprofile"),std::map<std::string,sdbus::Variant>()).uponReplyInvoke([](const sdbus::Error* error) {std::cerr << "profile registered\n"; });
`

libsystemd is 247.3-6 from debian bullseye

**Comment by akapelrud** [comment]
I realise this an old thread/issue, but did you install sdbus-cpp using apt or build from scratch? i.e. because the one in bullseye is an older release. I had to backport v1.20 from the sid sourcepackages to my bullseye installation to get `GetManagedObjects` to function correctly.

Essentially, using `cowbuilder`:

```
$ sudo apt install cowbuilder
$ sudo cowbuilder --create --distribution bullseye
```

Then get the source package
```
$ mkdir -p $HOME/src/sdbus-cpp && cd $HOME/src/sdbus-cpp
$ dget http://deb.debian.org/debian/pool/main/s/sdbus-cpp/sdbus-cpp_1.2.0-1.dsc
$ sudo cowbuilder --distribution bullseye --build sdbus-cpp_1.2.0-1.dsc
```
Then install the packages with `$ sudo dpkg -i /var/cache/pbuilder/result/libsdbus-c++*.deb`.

This took ~10 minutes on a Raspberry Pi 4.

This upgrade fixed a similar (if not identical) issue I had when trying to register a gatt service's object hierarchy (top level ObjectManager) using the `org.bluez.GattManager1` interface method `RegisterApplication`.

For completeness sake; the source code in 1.20 was **not** patched with the proposed fix in #246.

**Comment by akemnade** [comment]
What I did:
1. noticing this bug now with debian bullseye package
2. fixing it on top up that
3. reproducing it on master branch at that time
4. fixing it there and create PR and issue

And now I tried it again with current github master
It is still there and can still be fixed with my PR.

**Comment by sangelovic** [comment]
@akemnade I don't understand the provided example and the issue is not described sufficiently. Can you please be more specific and detail out the minimalist example, without dependencies on external D-Bus services, and with showing what the output is with sdbus-c++ from current master and what it according to you should be?

We have integration tests for object manager. [`SdbusTestObject.GetsZeroManagedObjectsIfHasNoSubPathObjects`](https://github.com/Kistler-Group/sdbus-cpp/blob/master/tests/integrationtests/DBusStandardInterfacesTests.cpp#L144) tests that `GetManagedObjects()` returns zero. [`SdbusTestObject.GetsManagedObjectsSuccessfully`](https://github.com/Kistler-Group/sdbus-cpp/blob/master/tests/integrationtests/DBusStandardInterfacesTests.cpp#L152) tests that `GetManagedObjects()` returns two -- the number of objects deeper in the path hierarchy. They work with no need of special enumerator of #246. Additionally, we have an example client-server application in the `examples` directory, which demonstrates the use and working of object manager functionality. All these work on my system with systemd v247. Have you run those? What are the results?

**Comment by akemnade** [comment]
ok that thing got totally misformatted, because I did not care for markdown.

So first the dbus-monitor --system output with/without that patch before I dig into the tests.

[patched-correct.txt](https://github.com/Kistler-Group/sdbus-cpp/files/10326175/patched-correct.txt)
[unpatched-failed.txt](https://github.com/Kistler-Group/sdbus-cpp/files/10326176/unpatched-failed.txt)

**Comment by sangelovic** [comment]
From the dbus-monitor output I still understand nothing. I have no idea how it relates to the example, why it should be the output of that example, and, at all, how the example relates to the object manager functionality. I'm not familiar with `org.bluez.*` stuff and this stuff is not part of sdbus-c++. I'm left to repeat my previous post before I close this issue as unrelated.

**Comment by akemnade** [comment]
I do not know why you need to know about org.bluez.* stuff to understand that and why you do not understand the problem. I show an unexpected behavior and the expected one. I played around a bit with the obj-manager-server.cpp example and did the following:
```
diff --git a/examples/org.freedesktop.DBus.ObjectManager/obj-manager-server.cpp b/examples/org.freedesktop.DBus.ObjectManager/obj-manager-server.cpp
index caadf52..ce986d7 100644
--- a/examples/org.freedesktop.DBus.ObjectManager/obj-manager-server.cpp
+++ b/examples/org.freedesktop.DBus.ObjectManager/obj-manager-server.cpp
@@ -85,7 +85,12 @@ int main()
     connection->requestName("org.sdbuscpp.examplemanager");
     connection->enterEventLoopAsync();
 
-    auto manager = std::make_unique<ManagerAdaptor>(*connection, "/org/sdbuscpp/examplemanager");
+    //auto manager = std::make_unique<ManagerAdaptor>(*connection, "/org/sdbuscpp/examplemanager");
+    auto managerobj = sdbus::createObject(*connection, "/org/sdbuscpp/examplemanager");
+    managerobj->addObjectManager();
+    managerobj->registerProperty("NonExisting").onInterface("org.sdbuscpp.nonexisting").withGetter([](){ return std::vector<std::string>({std::string("ThisDoesNotShowUp")});});
+    managerobj->finishRegistration();
+
     while (true)
     {
         printCountDown("Creating PlanetAdaptor in ", 5);
@@ -105,4 +110,4 @@ int main()
     connection->releaseName("org.sdbuscpp.examplemanager");
     connection->leaveEventLoop();
     return 0;
-}
\ No newline at end of file
+}
```
This gives these results on tests: the first one is  as expected.
```
$ dbus-send --print-reply --dest=org.sdbuscpp.examplemanager /org/sdbuscpp/examplemanager org.freedesktop.DBus.Properties.GetAll string:org.sdbuscpp.nonexisting | grep NonExist
         string "NonExisting"
```

the seconds one: 
```
dbus-send --print-reply --dest=org.sdbuscpp.examplemanager /org/sdbuscpp/examplemanager org.freedesktop.DBus.ObjectManager.GetManagedObjects | grep NonExist
```
gives just an empty result, I would expect returing also the "NonExisting"
Planet stuff is returned in all cases

**Comment by akapelrud** [comment]
@akemnade, I think you have misinterpreted the bluez api - [gatt-api.txt](https://github.com/bluez/bluez/blob/master/doc/gatt-api.txt).

Have a look at the section: "GATT Manager hierarchy". It clearly states that you need an `org.freedesktop.DBus.ObjectManager` at the root of your sub-hierarchy where you define your profile.:

Excerpt:
```
To make service registration simple, BlueZ requires that all objects that belong
to a GATT service be grouped under a D-Bus Object Manager that solely manages
the objects of that service. Hence, the standard DBus.ObjectManager interface
must be available on the root service path. An example application hierarchy
containing two separate GATT services may look like this:

-> /com/example
  |   - org.freedesktop.DBus.ObjectManager
  |
  -> /com/example/service0
  | |   - org.freedesktop.DBus.Properties
  | |   - org.bluez.GattService1
```
The same is true when registering a `org.bluez.GattProfile1` object.

If you add a parent object, at say `/org/ak/bleuart`, and make that the ObjectManager you will likely get the correct result.

**Comment by sangelovic** [comment]
@akemnade I now invested a little of very precious time of mine and dug out the missing pieces of information from that dbus-monitor output -- the pieces that should have been defined in this issue right from the start. From that I guess you want the return value of the `GetManagedObjects()` call on your `/org/ak/bleuart/bleprofile` object to contain the item about the `/org/ak/bleuart/bleprofile` itself. But that's not the behavior defined in the specification. Citing from the D-Bus specification:

> The return value of this method is a dict whose keys are object paths. All returned object paths are children of the object path implementing this interface, i.e. their object paths start with the ObjectManager's object path plus '/'.

You'll only get children from that call, not the root object itself. And sdbus-c++ behaves according to the specs. Anything to add before I close this as well as #246?

**Comment by akemnade** [comment]
yes, the spec is clear here. sdbus-c++ listens to the spec. And that is correct, so you can close this.
