### ISSUE TITLE
0.3.3 release doesn't build out of the box by unittests build

### ISSUE THREAD

**Issue by merhalak** [Kistler-Group/sdbus-cpp#28]
master is also affected by this issue:
```
sdbus-cpp/test/unittests/Types_test.cpp: In member function ‘virtual void AVariant_CanBeConstructedFromAComplexValue_Test::TestBody()’:
sdbus-cpp/test/unittests/Types_test.cpp:69:35: error: unnecessary parentheses in declaration of ‘value’ [-Werror=parentheses]
     ASSERT_NO_THROW(sdbus::Variant(value));
                                   ^
```

Possible fix there: merhalak@93248b80a2ea1f418f88e545fe933532c690a515

**Comment by sangelovic** [comment]
Hi, I guess you are compiling the library with gcc 8, right? I don't have that version at hand. Nevertheless, your proposal solves the issue with this warning, but the warning here is on a completely valid code anyway (using parentheses or braces when creating an object is equivalent here). So instead of bending already valid code just to please one specific warning of a specific compiler, the real solution now lies in removing warning-to-error compiler options from library CMakeLists. These should rather come from the user. See #31 , which will fix this issue.
