### ISSUE TITLE
sdbus-cpp can not receive PrepareForSleep signal

### ISSUE THREAD

**Issue by AceLearnGit** [Kistler-Group/sdbus-cpp#356]
**Describe the bug**
I use sdbus-cpp to listen PrepareForSleep signal like this:

#include <iostream>
#include <sdbus-c++/sdbus-c++.h>
using namespace std;

int main()
{
    const char *destinationName = "org.freedesktop.login1";
    const char *objectPath = "/org/freedesktop/login1";
    const char *interfaceName = "org.freedesktop.login1.Manager";
    const string signalName = "PrepareForSleep";

    auto proxy = sdbus::createProxy(destinationName, objectPath);
    proxy->uponSignal(signalName).onInterface(interfaceName).call([](bool flag) {cout << "Received the signal";});
    proxy->finishRegistration();
    while (true) {
        ;
    }
    return 0;
}

**To Reproduce**
Steps to reproduce the behavior.
build the demo and run it, then make system sleep,finaly wake up system
but the demo didn't cout anything.

**Expected behavior**
I expecte the demo print  "Received the signal" when system sleep
**Real (buggy) behavior**
A clear and concise description of what really happened in contrast to your expectation.
There is nothing print
**Additional context**
Add any other context about the problem here, like version of sdbus-c++ library, version of systemd used, OS used.
sdbus-cpp version:1.2.0
systemd version: 241

**Comment by sangelovic** [comment]
You don't send `std::cout` to the stream after writing "Received the signal". The signal may have been processed, but the message may have never been flushed and thus did not appear in the program output.

Additionally, you use busy waiting, taking an entire CPU core for just waiting. That's doesn't do good.

Otherwise I don't see a problem in the example. The signal should be listened to (provided that all the interface names, paths, etc. are correct, and that requirements like https://github.com/Kistler-Group/sdbus-cpp/blob/master/docs/systemd-dbus-config.md are fulfilled, and provided that the signal is really emitted (may be verified with `dbus-monitor`)).

**Comment by AceLearnGit** [comment]
I found the problem.
To recv PrepareForSleep signal, we need to call Inhibit method first to get a Inhibitor Lock first.
