### ISSUE TITLE
using enterProcessingLoopAsync() does not create the DBus Object when defining a DBus Service

### ISSUE THREAD

**Issue by yamo-goe** [Kistler-Group/sdbus-cpp#37]
Using the enterProcessingLoopAsyc() function does not create the DBus Object for a defined Service, whereas enterProcessingLoop() does create the Object as expected.
My code looks like this:
```
void registerDBusService() {
    serviceConnection = sdbus::createSystemBusConnection(serviceServiceName.c_str());
    auto _serviceObject = sdbus::createObject(*serviceConnection, serviceObjectPath.c_str());
    service = _serviceObject.get();
    service->registerMethod("Connect").onInterface(serviceInterface).implementedAs(serviceConnect);
    service->registerMethod("Disconnect").onInterface(serviceInterface).implementedAs(serviceDisconnect);
    service->registerMethod("Restart").onInterface(serviceInterface).implementedAs(serviceRestart);
    service->registerMethod("Status").onInterface(serviceInterface).implementedAs(serviceStatus);
    service->finishRegistration();
    serviceConnection->enterProcessingLoopAsync(); //fails to create the DBus Object
}
```

**Comment by sangelovic** [comment]
Hello, sorry, this issue somehow ended beyond my radar until now. The problem in your code is that you are creating `_serviceObject`, which technically is a `unique_ptr` to object instance, then you store a raw pointer to `service`, and do the registration, and run the processing loop. All fine until now. The problem is that at the end of `registerDBusService` function, the `_serviceObject` gets destructed, as it a local scope variable. With this, the entire D-Bus object gets destructed, and `service` becomes a dangling pointer.

What you could do is change `service` type to `std::unique_ptr<sdbus::IObject>` and when creating the object, assign the result to `service` directly: `service = sdbus::createObject(*serviceConnection, serviceObjectPath.c_str());`

**Comment by sangelovic** [comment]
Let me know if this worked for you.
