### ISSUE TITLE
Allow moving ProxyInterfaces

### ISSUE THREAD

**Issue by 17steen** [Kistler-Group/sdbus-cpp#383]
**Is your feature request related to a problem? Please describe.**
It would be very useful if the proxies could be moved,
as of now I have to wrap them in a unique_ptr<> to do so, which adds another indirection on top of
the `unique_ptr<IProxy>` that the class contains.

**Describe the solution you'd like**
being able to std::move() a class inheriting from ProxyInterfaces

**Describe alternatives you've considered**
wrapping inside a unique_ptr<>

**Additional context**
Example of code that doesn't work:
```cpp
            auto device = device_t{std::move(device_path)};

            // See https://upower.freedesktop.org/docs/Device.html
            const auto type = device.Type();

            static constexpr auto BATTERY_TYPE = 2u;
            static constexpr auto UPS_TYPE = 3u;

            const bool is_power_supply = device.PowerSupply();

            if ((type == BATTERY_TYPE || type == UPS_TYPE) && is_power_supply)
            {
                batteries.push_back(std::move(device)); // doesn't compile
                println("Adding `{}` to the list of batteries.", device.NativePath());
            }
```

**Comment by sangelovic** [comment]
sdbus-c++ has added support for move semantics of the Proxy and Adaptor classes since [v1.3.0](https://github.com/Kistler-Group/sdbus-cpp/releases/tag/v1.3.0). See [this commit](https://github.com/Kistler-Group/sdbus-cpp/commit/aeae7900) specifically. That this works is verified in the integration tests [here](https://github.com/Kistler-Group/sdbus-cpp/blob/master/tests/integrationtests/DBusGeneralTests.cpp#L64-L74).

Make sure you are using sdbus-c++ v1.3.0 or later. Btw., you haven't specified the type of `device_t` in your example, I only guess it's a class inheriting from `sdbus::ProxyInterfaces`.

**Comment by 17steen** [comment]
My bad for not checking with the latest version, sorry for the bother, and thanks for showing me what works
