### ISSUE TITLE
Sporadic missed NameAcquired signal if requestName called after enterEventLoopAsync

### ISSUE THREAD

**Issue by anthonybrandon** [Kistler-Group/sdbus-cpp#390]
**Describe the bug**
When calling requestName on a different thread from the one running the event loop, after the event loop is started
there is a small chance of missing the NameAcquired signal that is sent in response to requestName.

**To Reproduce**

* Create a connection
* start the event loop (on another thread)
* register to the NameAcquired signal
* call requestName

```cpp
TEST(Connection, NameAcquiredSignal)
{
    std::promise<void> promise;
    auto connection = sdbus::createSessionBusConnection();
    connection->enterEventLoopAsync();
    auto dbusProxy = sdbus::createProxy(*connection, "org.freedesktop.DBus", "/org/freedesktop/DBus");
    dbusProxy->uponSignal("NameAcquired")
        .onInterface("org.freedesktop.DBus")
        .call([&promise](const std::string& name)
        { promise.set_value(); });
    dbusProxy->finishRegistration();

    connection->requestName("com.test.test");

    EXPECT_EQ(std::future_status::ready, promise.get_future().wait_for(std::chrono::seconds(1)));
}
```

**Expected behavior**

NameAcquired signal should be received

**Real (buggy) behavior**

Occasionally (once every several 100 times for me) the signal is not received.
To be more accurate, the signal is received, but never processed by the event loop, and so the callback is not called.

**Additional context**

The problem seems to be with `sd_bus_request_name`.
This is a sync call, but does not handle the case of a running event loop like `tryCallMethodSynchronously` does for example.
Calling `notifyEventLoop(eventFd_.fd)` after calling `sd_bus_request_name` seems to solve it.
A similar issue may exist with releaseName.
There might be some other solution like making requestName aware of the event loop, or providing a requestNameAsync.

**Comment by sangelovic** [comment]
@anthonybrandon Very good observation and well described issue. Indeed, `requestName` and `releaseName` methods perform a synchronous call, and suffer from that problem. We just forgot about them when solving this problem generally for sync calls, because they do it in a special way directly through dedicated sd-bus API.

One solution would be to rewrite them to use sdbus-c++ API (to construct a method call message, serialize arguments into it, and send it). I prefer to use the convenience of sd-bus here and instead notify the event loop after the call -- see PR #392. 

sdbus-c++ v2 (currently in working branch `release/v2.0`) has the handling of event loops in context of multi-threading simplified and refactored, and the solution there will be a little nicer (it will first check if any new messages have arrived at the input queue, and if so it would then wake up the event loop).

I also plan to implement async variants of both methods.

Thanks for submitting this issue!

**Comment by anthonybrandon** [comment]
@sangelovic You're welcome. I'm looking forward to the v2.0 release :)
