### ISSUE TITLE
doesn't notice signal without method call

### ISSUE THREAD

**Issue by FuchtelJockel** [Kistler-Group/sdbus-cpp#391]
I want to subscribe to a response signal which triggers after a method call. The signal and method have different object paths and interfaces. My solution is:

1. create a proxy for the signal
2. subscribe to signal
3. create proxy for method call
4. call method
5. expect signal call

I expect to get the signal after calling the method but nothing gets received. dbus-monitor shows a successful method call and the signal was send.
It seems like signals get ignored if no method gets called on a proxy.
I'm probably misunderstanding the library but I can't find documentation for my use case.
I implemented the same functionality in rust with the zbus library and it works as expected.

Version: 1.2.0
example file: [main.txt](https://github.com/Kistler-Group/sdbus-cpp/files/13693992/main.txt)

**Comment by sangelovic** [comment]
The problem is that no event loop was run in your example for the `connection`. One must call `enterEventLoop()` or `enterEventLoopAsync()` method of the `connection` object. Perhaps that is not specified clearly in the sdbus-c++ tutorial...

**Comment by sangelovic** [comment]
Or you can simply create `sessionResponse` like this: `auto sessionResponse = sdbus::createProxy(sdbus::createSessionBusConnection(), destinationName, sessionResponsePath);`, which, according to https://github.com/Kistler-Group/sdbus-cpp/blob/master/docs/using-sdbus-c%2B%2B.md#using-d-bus-connections-on-the-client-side means that the proxy will get an owner of the connection and will automatically run the event loop on it for your convenience (hence signals would work fine for you), and create `createSession` like this: `auto createSession = sdbus::createProxy(sdbus::createSessionBusConnection(), destinationName, objectPath, sdbus::dont_run_event_loop_thread);`, which has the proxy create another connection, but whose event loop would not be run because you just use it to call a method and then let go of it, as described again in https://github.com/Kistler-Group/sdbus-cpp/blob/master/docs/using-sdbus-c%2B%2B.md#using-d-bus-connections-on-the-server-side, so this saves time and resources.

**Comment by FuchtelJockel** [comment]
That was quick, thanks. I only looked at the client side of the tutorials. Now I see and it works.

**Comment by sangelovic** [comment]
Out of curiosity, how does this example look in rust with the zbus library? Can you paste the code? I wonder if I can simplify anything here :-)

**Comment by FuchtelJockel** [comment]
Very similar but with more macro magic. [main.txt](https://github.com/Kistler-Group/sdbus-cpp/files/13694102/main.txt)

The official example is probably more helpful than my code: https://dbus2.github.io/zbus/client.html

**Comment by sangelovic** [comment]
@FuchtelJockel I think that would be possible in sdbus-c++, too. The user would, however, need to additionally describe his struct (through some sort of sdbus-c++-provided macros, for example) so that sdbus-c++ would know understand the struct's members, their names, position etc.

**Comment by sangelovic** [comment]
Hey @FuchtelJockel for your information, since a few months ago, sdbus-c++ v2 has been providing the `SDBUSCPP_REGISTER_STRUCT` macro that enables to use user-defined structs, not only `sdbus::Struct`, as fully valid representation of D-Bus struct type. Now this merge request: https://github.com/Kistler-Group/sdbus-cpp/pull/459 is extending that macro with the built-in functionality of serializing user-defined structs as `a{sv}` dictionaries (when decorated with `as_dictionary(struct)`), and deserializing `a{sv}` dictionaries into user-defined structs (automatically). I'm just giving you heads-up because you mentioned the feature above (with reference to zbus) and now that feature is about to be integrated into sdbus-c++ v2 :-)

More info about the new feature here: https://github.com/Kistler-Group/sdbus-cpp/blob/feat/struct-as-dict-serialization/docs/using-sdbus-c%2B%2B.md#adding-user-defined-types-to-the-sdbus-c-type-system

If you have any comments or if some functionality is missing, let me know ;-) Thanks

**Comment by FuchtelJockel** [comment]
Thanks for letting me know. This look great, but  sadly I don't work on that project anymore.
If I have any dbus needs in the future, I will definitely come back to this project :)
