### ISSUE TITLE
High-Level (stub) Support for PropertiesChanged signal

### ISSUE THREAD

**Issue by riuriuriu** [Kistler-Group/sdbus-cpp#85]
Hey Stano, I hope you are doing well.

I recently had to observe D-Bus properties for changes and was able do do it with sdbus-cpp. Nevertheless I was wondering if there could be a more convenient way to do it. Maybe I just didn't see it.

The generated client stub code provides nice methods to get/set the property, depending on the chosen `access` attribute in the IDL. Nevertheless it **doesn't** provide callbacks or similar means to inform the client if a property changes it's value.

It was possible to implement the observer functionality via the basic API layer by registering for `PropertiesChanged` on the `org.freedesktop.DBus.Properties` interface. Nevertheless I needed to create a separate `sdbus::IProxy` instance as the generated stub or the `sdbus::ProxyInterfaces` do not give public access to it's `sdbus::IProxy`. I think the extra proxy is not that much a problem since we can provide the same `sdbus::IConnection` for both instances and therefore use the same event loop. Nevertheless I was wondering if:

- There is already a more convenient way to observe a property?
- If not, could the generated stub code provide a convenient way? How would it look like? Maybe someone at Kistler finds the time to implement it.
- Is there a reason the `sdbus::IProxy` of the stub is not exposed so we can't register further signals on it manually?

Kind Regards
Urs

**Comment by sangelovic** [comment]
Hi Urs.

Thanks for being patient :o)

sdbus-c++ provides classes representing standard D-Bus interfaces for
generated adaptors/proxies (including org.freedesktop.DBus.Properties).
Look into
https://github.com/Kistler-Group/sdbus-cpp/blob/master/include/sdbus-c%2B%2B/StandardInterfaces.h
public header file, and also in tutorial:
https://github.com/Kistler-Group/sdbus-cpp/blob/master/docs/using-sdbus-c%2B%2B.md

Simply add Properties_proxy and Properties_adaptor from there into the list
of parameter types in your ProxyInterfaces/AdaptorInterfaces
implementation. In case of proxy, simply override the onPropertiesChanged
virtual function in your proxy implementation.

To your third question, IProxy reference is available as a ctor parameter
to interface classes, because (only) these classes should do registration.

Hope it helped?

Stano.

**Comment by riuriuriu** [comment]
Thanks, that exactly answers what I needed to know.

I probably read this part of the tutorial too quick and was looking for examples rather than text. If I find the time, I can contribute a tutorial example about how to use the standard D-Bus interfaces.
